export const CountryMapping = {
    'Argentina': 'ar',
    'Australia': 'au',
    'Austria': 'at',
    'Belgium': 'be',
    'Brazil': 'br',
    'Bulgaria': 'bg',
    'Canada': 'ca',
    'Chile': 'cl',
    'Croatia': 'hr',
    'Czech Republic': 'cz',
    'Denmark': 'dk',
    'Egypt': 'eg',
    'Finland': 'fi',
    'France': 'fr',
    'Germany': 'de',
    'Greece': 'gr',
    'Hungary': 'hu',
    'India': 'in',
    'Ireland': 'ie',
    'Israel': 'il',
    'Italy': 'it',
    'Japan': 'jp',
    'Korea': 'kr',
    'Mexico': 'mx',
    'Morocco': 'ma',
    'Netherlands': 'nl',
    'New Zealand': 'nz',
    'Norway': 'no',
    'Pakistan': 'pk',
    'Poland': 'pl',
    'Portugal': 'pt',
    'Romania': 'ro',
    'Russia': 'ru',
    'Serbia': 'rs',
    'Slovakia': 'sk',
    'Spain': 'es',
    'Sweden': 'se',
    'Switzerland': 'ch',
    'United Kingdom': 'gb',
    'Ukraine': 'ua',
    'United States': 'us',
    'World': 'world',
}

export type Country = keyof typeof CountryMapping
