name: Check

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - master

jobs:
  check:
    if: "!contains(github.event.head_commit.message, 'chore: release')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Use Node.js v16
        uses: actions/setup-node@v4
        with:
          node-version: '16'
          registry-url: https://registry.npmjs.org/
          cache: pnpm

      - run: pnpm install

      - name: Build
        run: pnpm run build

      - name: Lint
        run: pnpm run lint

      - name: Test
        run: pnpm run test
